// lib/services/xml/xml_generator.dart

import 'package:xml/xml.dart' as xml;
import '../../data/models/odoo_form.dart';

/// Core service for generating Odoo-compatible XML from OdooView models.
///
/// Produces clean, pretty-printed XML that is 100% compatible with
/// Odoo 14.0+ view definitions.
class XmlGenerator {
  XmlGenerator._();

  // ─── Public API ──────────────────────────────────────────────────────────────

  /// Generate a complete views.xml file containing one or more views.
  static String generateFile(List<OdooView> views, {String? moduleName}) {
    final buf = StringBuffer();
    buf.writeln('<?xml version="1.0" encoding="utf-8"?>');
    buf.writeln('<!-- Generated by Odoo View Builder -->');
    if (moduleName != null) {
      buf.writeln('<!-- Module: $moduleName -->');
    }
    buf.writeln('<!-- Generated on: ${DateTime.now().toUtc()} -->');
    buf.writeln();
    buf.writeln('<odoo>');
    buf.writeln('    <data>');

    for (int i = 0; i < views.length; i++) {
      if (i > 0) buf.writeln();
      buf.writeln('        <!-- View: ${views[i].name} (${views[i].model}) -->');
      buf.write(_generateRecord(views[i]));
    }

    buf.writeln();
    buf.writeln('    </data>');
    buf.write('</odoo>');
    return buf.toString();
  }

  /// Generate XML for a single view (wrapped in <?xml ...?><odoo>)
  static String generateSingle(OdooView view) {
    return view.generateXml();
  }

  /// Generate only the <arch> content (without record wrapper)
  static String generateArch(OdooView view) {
    return switch (view.viewType) {
      ViewType.form => _buildFormArch(view, baseIndent: 0),
      ViewType.tree => _buildTreeArch(view, baseIndent: 0),
      ViewType.kanban => _buildKanbanArch(view, baseIndent: 0),
    };
  }

  // ─── Record Generation ───────────────────────────────────────────────────────

  static String _generateRecord(OdooView view) {
    final buf = StringBuffer();
    buf.writeln('        <record id="${view.id}" model="ir.ui.view">');
    buf.writeln('            <field name="name">${view.name}</field>');
    buf.writeln('            <field name="model">${view.model}</field>');

    if (view.priority != 16) {
      buf.writeln('            <field name="priority" eval="${view.priority}"/>');
    }

    if (view.inheritId != null && view.inheritId!.isNotEmpty) {
      buf.writeln('            <field name="inherit_id" ref="${view.inheritId}"/>');
    }

    buf.writeln('            <field name="arch" type="xml">');

    buf.write(switch (view.viewType) {
      ViewType.form => _buildFormArch(view, baseIndent: 16),
      ViewType.tree => _buildTreeArch(view, baseIndent: 16),
      ViewType.kanban => _buildKanbanArch(view, baseIndent: 16),
    });

    buf.writeln('            </field>');
    buf.write('        </record>');
    return buf.toString();
  }

  // ─── Form View ───────────────────────────────────────────────────────────────

  static String _buildFormArch(OdooView view, {required int baseIndent}) {
    final i = _indent(baseIndent);
    final i4 = _indent(baseIndent + 4);
    final buf = StringBuffer();

    buf.writeln('$i<form>');

    // Custom CSS
    if (view.customCSS != null && view.customCSS!.isNotEmpty) {
      buf.writeln('$i4<style>${view.customCSS}</style>');
    }

    // Top-level fields (outside groups)
    for (final f in view.topLevelFields) {
      buf.writeln(f.toXml(indent: baseIndent + 4));
    }

    // Groups
    for (final g in view.groups) {
      buf.write(g.toXml(indent: baseIndent + 4));
    }

    // Notebook pages
    if (view.pages.isNotEmpty) {
      buf.writeln('$i4<notebook>');
      for (final page in view.pages) {
        _buildPage(buf, page, indent: baseIndent + 8);
      }
      buf.writeln('$i4</notebook>');
    }

    buf.write('$i</form>');
    return buf.toString();
  }

  static void _buildPage(
    StringBuffer buf,
    NotebookPage page, {
    required int indent,
  }) {
    final i = _indent(indent);

    final invisAttr = page.invisible == true ? ' invisible="1"' : '';
    buf.writeln('$i<page string="${page.label}"$invisAttr>');

    for (final f in page.fields) {
      buf.writeln(f.toXml(indent: indent + 4));
    }

    for (final g in page.groups) {
      buf.write(g.toXml(indent: indent + 4));
    }

    buf.writeln('$i</page>');
  }

  // ─── Tree View ───────────────────────────────────────────────────────────────

  static String _buildTreeArch(OdooView view, {required int baseIndent}) {
    final i = _indent(baseIndent);
    final buf = StringBuffer();

    final attrs = StringBuffer();
    if (view.editable) attrs.write(' editable="top"');
    if (view.defaultOrder != null && view.defaultOrder!.isNotEmpty) {
      attrs.write(' default_order="${view.defaultOrder}"');
    }

    buf.writeln('$i<tree$attrs>');

    for (final f in view.topLevelFields) {
      buf.writeln(f.toXml(indent: baseIndent + 4));
    }

    buf.write('$i</tree>');
    return buf.toString();
  }

  // ─── Kanban View ─────────────────────────────────────────────────────────────

  static String _buildKanbanArch(OdooView view, {required int baseIndent}) {
    final i = _indent(baseIndent);
    final i4 = _indent(baseIndent + 4);
    final i8 = _indent(baseIndent + 8);
    final i12 = _indent(baseIndent + 12);
    final i16 = _indent(baseIndent + 16);
    final buf = StringBuffer();

    final classAttr = view.kanbanClass != null && view.kanbanClass!.isNotEmpty
        ? ' class="${view.kanbanClass}"'
        : '';
    buf.writeln('$i<kanban$classAttr>');

    // field declarations
    for (final f in view.topLevelFields) {
      buf.writeln('$i4<field name="${f.name}"/>');
    }

    buf.writeln('$i4<templates>');
    buf.writeln('$i8<t t-name="kanban-box">');
    buf.writeln('$i12<div class="oe_kanban_global_click">');

    for (final f in view.topLevelFields.where((f) => !f.invisible)) {
      buf.writeln('$i16<div class="oe_kanban_details">');
      buf.writeln('$i16    <field name="${f.name}"/>');
      buf.writeln('$i16</div>');
    }

    buf.writeln('$i12</div>');
    buf.writeln('$i8</t>');
    buf.writeln('$i4</templates>');
    buf.write('$i</kanban>');
    return buf.toString();
  }

  // ─── Utilities ───────────────────────────────────────────────────────────────

  static String _indent(int n) => ' ' * n;

  /// Validate that a string is well-formed XML
  static bool isValidXml(String content) {
    try {
      // Basic structural check (no external dependency needed)
      // A proper XML validator using the `xml` package can be injected here
      if (!content.trim().startsWith('<')) return false;
      // Check balanced tags roughly
      int opens = '<'.allMatches(content).length -
          '</'.allMatches(content).length -
          '/>'.allMatches(content).length;
      return opens >= 0;
    } catch (_) {
      return false;
    }
  }

  /// Returns `true` if [xmlStr] is well-formed XML, `false` otherwise.
  ///
  /// Uses the `xml` package for strict parsing.
  static bool validateXml(String xmlStr) {
    if (xmlStr.trim().isEmpty) return false;
    try {
      xml.XmlDocument.parse(xmlStr);
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Escape special XML characters in a text value
  static String escape(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }

  /// Pretty-format raw XML string (basic indentation)
  static String prettyPrint(String raw) {
    final result = StringBuffer();
    int indent = 0;

    final tagPattern = RegExp(
      r'(<[^>]+>)|([^<]+)',
      multiLine: true,
    );

    for (final match in tagPattern.allMatches(raw)) {
      final tag = match.group(1);
      final text = match.group(2);

      if (tag != null) {
        final isClose = tag.startsWith('</');
        final isSelfClose = tag.endsWith('/>');
        final isComment = tag.startsWith('<!--');
        final isDecl = tag.startsWith('<?');

        if (isClose) indent = (indent - 1).clamp(0, 100);

        result.write('${' ' * (indent * 4)}$tag\n');

        if (!isClose && !isSelfClose && !isComment && !isDecl) indent++;
      } else if (text != null && text.trim().isNotEmpty) {
        result.write('${' ' * (indent * 4)}${text.trim()}\n');
      }
    }

    return result.toString().trimRight();
  }
}
