// lib/main.dart
//
// Application entry point.
//
// Initialisation order:
//   1. WidgetsFlutterBinding
//   2. CrashReporter  — must be set up BEFORE runApp so uncaught errors
//      from widget building are captured.
//   3. AnalyticsService
//   4. FlutterError.onError override
//   5. runZonedGuarded → runApp(ProviderScope(…))
//
// Firebase note
// ─────────────
// Firebase is OPTIONAL. To enable it:
//   1. Run `flutterfire configure`.
//   2. Uncomment the firebase_core / analytics / crashlytics lines in pubspec.yaml.
//   3. Uncomment the `Firebase.initializeApp` call below.
//   4. Pass `useFirebase: true` to `CrashReporter.init()` and `AnalyticsService.init()`.

import 'dart:async';
import 'dart:isolate';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:logging/logging.dart';

import 'app.dart';
import 'services/analytics/analytics_service.dart';
import 'services/analytics/crash_reporter.dart';

// ── Conditional Firebase import ──────────────────────────────────────────
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // generated by flutterfire configure

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

Future<void> main() async {
  // ── Step 1: Ensure Flutter bindings ─────────────────────────────────────
  WidgetsFlutterBinding.ensureInitialized();

  // ── Step 2: Configure logger ─────────────────────────────────────────────
  _setupLogging();

  // ── Step 3: Firebase (optional) ─────────────────────────────────────────
  // await Firebase.initializeApp(
  //   options: DefaultFirebaseOptions.currentPlatform,
  // );

  // ── Step 4: CrashReporter ────────────────────────────────────────────────
  await CrashReporter.init(useCrashlytics: false /* set true when Firebase is configured */);

  // ── Step 5: Analytics ────────────────────────────────────────────────────
  await AnalyticsService.init(useFirebase: false /* set true when Firebase is configured */);

  // ── Step 6: Flutter framework error hook ─────────────────────────────────
  FlutterError.onError = CrashReporter.instance.onFlutterError;

  // ── Step 7: Platform-specific orientation ────────────────────────────────
  if (!kIsWeb) {
    // Allow both orientations on mobile; desktop handles this automatically.
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
      DeviceOrientation.landscapeLeft,
      DeviceOrientation.landscapeRight,
    ]);
  }

  // ── Step 8: System UI style ───────────────────────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
    ),
  );

  // ── Step 9: Log app start ─────────────────────────────────────────────────
  await AnalyticsService.instance.logEvent(AnalyticsEvents.appOpened);

  // ── Step 10: Run app inside error zone ───────────────────────────────────
  await _runApp();
}

// ---------------------------------------------------------------------------
// _runApp
// ---------------------------------------------------------------------------

Future<void> _runApp() async {
  await runZonedGuarded<Future<void>>(
    () async {
      runApp(
        const ProviderScope(
          child: OdooViewBuilderApp(),
        ),
      );
    },
    (error, stack) {
      // Catch errors from the Dart zone (async errors not caught by Flutter).
      CrashReporter.instance.recordFatal(error, stack);
    },
  );

  // Also install an isolate error listener for background isolate crashes.
  _installIsolateErrorHandler();
}

// ---------------------------------------------------------------------------
// _installIsolateErrorHandler
// ---------------------------------------------------------------------------

void _installIsolateErrorHandler() {
  final errorPort = RawReceivePort((dynamic pair) {
    if (pair is List && pair.length == 2) {
      final dynamic error = pair[0];
      final String? stackString = pair[1] as String?;
      CrashReporter.instance.recordFatal(
        (error as Object?) ?? 'Unknown isolate error',
        stackString != null
            ? StackTrace.fromString(stackString)
            : StackTrace.empty,
      );
    }
  });

  Isolate.current.addErrorListener(errorPort.sendPort);
}

// ---------------------------------------------------------------------------
// _setupLogging
// ---------------------------------------------------------------------------

void _setupLogging() {
  Logger.root.level = kDebugMode ? Level.ALL : Level.WARNING;

  Logger.root.onRecord.listen((record) {
    if (record.level >= Level.WARNING) {
      debugPrint(
          '[${record.level.name}] ${record.loggerName}: ${record.message}'
          '${record.error != null ? '\n  ${record.error}' : ''}'
          '${record.stackTrace != null ? '\n  ${record.stackTrace}' : ''}');
    } else if (kDebugMode) {
      debugPrint('[${record.level.name}] ${record.loggerName}: ${record.message}');
    }
  });
}
